version: '3.8'

services:
  b5-proxy:
    image: openresty/openresty:bullseye
    container_name: b5-proxy
    environment:
      B5_MODE: blocking
    ports:
      - "8080:80"
      - "8443:443"
    entrypoint:
      - sh
      - -c
      - |
        touch /usr/local/openresty/nginx/logs/waf_events.log
        chmod 666 /usr/local/openresty/nginx/logs/waf_events.log
        exec /usr/local/openresty/bin/openresty -g 'daemon off;'
    volumes:
      - ./proxy/conf:/usr/local/openresty/nginx/conf/
      - ./proxy/lua:/usr/local/openresty/nginx/lua/
      - ./proxy/logs:/usr/local/openresty/nginx/logs/
    depends_on:
      - b5-redis
    networks:
      - b5-network

  b5-redis:
    image: redis:alpine
    container_name: b5-redis
    ports:
      - "6379:6379"
    networks:
      - b5-network

  b5-postgres:
    image: postgres:15-alpine
    container_name: b5-postgres
    environment:
      POSTGRES_USER: b5admin
      POSTGRES_PASSWORD: b5password
      POSTGRES_DB: b5
    ports:
      - "5433:5432"
    volumes:
      - b5-db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - b5-network

  b5-backend:
    build: ./backend
    container_name: b5-backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=b5admin
      - POSTGRES_PASSWORD=b5password
      - POSTGRES_SERVER=b5-postgres
      - POSTGRES_DB=b5
      - REDIS_HOST=b5-redis
    volumes:
      - ./backend:/app
    depends_on:
      - b5-postgres
      - b5-redis
    networks:
      - b5-network

  # A simple target application to test the proxy
  dummy-app:
    image: nginx:alpine
    container_name: dummy-app
    volumes:
      - ./dummy-app/index.html:/usr/share/nginx/html/index.html
    networks:
      - b5-network

  b5-frontend:
    build: ./frontend
    container_name: b5-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - b5-backend
    networks:
      - b5-network

volumes:
  b5-db-data:

networks:
  b5-network:
    driver: bridge
