"""add_rate_limit_config_and_endpoint_config

Revision ID: ae3eb2590e68
Revises: 6a2f58eb9447
Create Date: 2026-05-03 10:44:00.373337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3eb2590e68'
down_revision: Union[str, Sequence[str], None] = '6a2f58eb9447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endpoint_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_prefix', sa.String(), nullable=False),
    sa.Column('allowed_methods', sa.String(), nullable=False),
    sa.Column('allowed_content_types', sa.String(), nullable=True),
    sa.Column('require_auth', sa.Boolean(), nullable=True),
    sa.Column('strict_mode', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_configs_enabled'), 'endpoint_configs', ['enabled'], unique=False)
    op.create_index(op.f('ix_endpoint_configs_id'), 'endpoint_configs', ['id'], unique=False)
    op.create_index(op.f('ix_endpoint_configs_path_prefix'), 'endpoint_configs', ['path_prefix'], unique=False)
    op.create_index(op.f('ix_endpoint_configs_policy_id'), 'endpoint_configs', ['policy_id'], unique=False)
    op.create_table('rate_limit_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('identifier_type', sa.String(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_configs_enabled'), 'rate_limit_configs', ['enabled'], unique=False)
    op.create_index(op.f('ix_rate_limit_configs_id'), 'rate_limit_configs', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limit_configs_identifier'), 'rate_limit_configs', ['identifier'], unique=False)
    op.create_index(op.f('ix_rate_limit_configs_identifier_type'), 'rate_limit_configs', ['identifier_type'], unique=False)
    op.create_index(op.f('ix_rate_limit_configs_policy_id'), 'rate_limit_configs', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_configs_policy_id'), table_name='rate_limit_configs')
    op.drop_index(op.f('ix_rate_limit_configs_identifier_type'), table_name='rate_limit_configs')
    op.drop_index(op.f('ix_rate_limit_configs_identifier'), table_name='rate_limit_configs')
    op.drop_index(op.f('ix_rate_limit_configs_id'), table_name='rate_limit_configs')
    op.drop_index(op.f('ix_rate_limit_configs_enabled'), table_name='rate_limit_configs')
    op.drop_table('rate_limit_configs')
    op.drop_index(op.f('ix_endpoint_configs_policy_id'), table_name='endpoint_configs')
    op.drop_index(op.f('ix_endpoint_configs_path_prefix'), table_name='endpoint_configs')
    op.drop_index(op.f('ix_endpoint_configs_id'), table_name='endpoint_configs')
    op.drop_index(op.f('ix_endpoint_configs_enabled'), table_name='endpoint_configs')
    op.drop_table('endpoint_configs')
    # ### end Alembic commands ###
